name: Build and push to ACR & GitHub

env:
  AZURE_WEBAPP_NAME: dockerosaurus

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: 'read'
  packages: 'write'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1


      - name: Log in to ACR container registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ${{ secrets.DOCKEROSAURUS_ACR_LOGIN_SERVER }}
          username: ${{ secrets.DOCKEROSAURUS_ACR_USERNAME }}
          password: ${{ secrets.DOCKEROSAURUS_ACR_PASSWORD }}
          
      - name: Log in to GitHub container registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compose ACR image tag name
        run: echo "ACR_TAG=$${{ secrets.DOCKEROSAURUS_ACR_LOGIN_SERVER }}/dockerosaurus:${{ github.sha }}" >>${GITHUB_ENV}
        
      - name: Lowercase the GitHub repo name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Build and push container image to ACR
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            env.ACR_TAG
            ghcr.io/${{ env.REPO }}:${{ github.sha }}
          file: ./Dockerfile
