name: Build and push to ACR & GitHub

env:
  AZURE_WEBAPP_NAME: dockerosaurus
  ACR_LOGIN_SERVER: "dockerosaurusacr.azurecr.io"

on:
  release:
    types: [published]

permissions:
  contents: 'read'
  packages: 'write'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1


      - name: Log in to ACR container registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ${{ env.ACR_LOGIN_SERVER }}
          username: ${{ secrets.DOCKEROSAURUS_ACR_USERNAME }}
          password: ${{ secrets.DOCKEROSAURUS_ACR_PASSWORD }}
          
      - name: Log in to GitHub container registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compose ACR image repository name
        run: |
          echo "ACR_REPO_FULL_NAME=${{ env.ACR_LOGIN_SERVER }}/dockerosaurus" >>${GITHUB_ENV}
        
      - name: Lowercase the GitHub repo name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Build and push container image to ACR and GitHub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ env.ACR_REPO_FULL_NAME }}:${{ github.sha }}
            ${{ env.ACR_REPO_FULL_NAME }}:${{ github.ref_name	}}
            ghcr.io/${{ env.REPO }}:${{ github.sha }}
            ghcr.io/${{ env.REPO }}:${{ github.ref_name }}
          file: ./Dockerfile
